CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppCinemaBooking.Areas.Admin.Models
{
    public class Room
    {
        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage = "Tên không được bỏ trống")] public string Name { get; set; }
        [Required(ErrorMessage = "Sức chứa không được bỏ trống")] public int Capacity { get; set; }
        [Required(ErrorMessage = "Trạng thái không được bỏ trống")] public int Status { get; set; }
        [Required(ErrorMessage = "Rạp Phim không được bỏ trống")] public int Cinema_ID { get; set; }
        [ForeignKey("Cinema_ID")]

        public virtual Cinema Cinema { get; set; }
    }
}

CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAppCinemaBooking.Areas.Admin.Data;
using WebAppCinemaBooking.Areas.Admin.Models;

namespace WebAppCinemaBooking.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RoomsController : Controller
    {
        private readonly DPContext _context;

        public RoomsController(DPContext context)
        {
            _context = context;
        }

        // GET: Admin/Rooms
        public async Task<IActionResult> Index()
        {
            var dPContext = _context.Rooms.Include(r => r.Cinema);
            return View(await dPContext.ToListAsync());
        }

        // GET: Admin/Rooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .Include(r => r.Cinema)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Admin/Rooms/Create
        public IActionResult Create()
        {
            ViewData["Cinema_ID"] = new SelectList(_context.Cinemas, "ID", "Name");
            return View();
        }

        // POST: Admin/Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Capacity,Status,Cinema_ID")] Room room)
        {
            if (ModelState.IsValid)
            {
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Cinema_ID"] = new SelectList(_context.Cinemas, "ID", "Name", room.Cinema_ID);
            return View(room);
        }

        // GET: Admin/Rooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            ViewData["Cinema_ID"] = new SelectList(_context.Cinemas, "ID", "Name", room.Cinema_ID);
            return View(room);
        }

        // POST: Admin/Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Capacity,Status,Cinema_ID")] Room room)
        {
            if (id != room.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Cinema_ID"] = new SelectList(_context.Cinemas, "ID", "Name", room.Cinema_ID);
            return View(room);
        }

        // GET: Admin/Rooms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .Include(r => r.Cinema)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Admin/Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var room = await _context.Rooms.FindAsync(id);
            _context.Rooms.Remove(room);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
            return _context.Rooms.Any(e => e.ID == id);
        }
        public async Task<IActionResult> Active(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.ID == id);
            if (room == null)
            {
                return NotFound();
            }
            room.Status = 1;
            _context.Rooms.Update(room);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UnActive(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.ID == id);
            if (room == null)
            {
                return NotFound();
            }
            room.Status = 0;
            _context.Rooms.Update(room);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Controllers/SeatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAppCinemaBooking.Areas.Admin.Data;
using WebAppCinemaBooking.Areas.Admin.Models;

namespace WebAppCinemaBooking.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SeatsController : Controller
    {
        private readonly DPContext _context;

        public SeatsController(DPContext context)
        {
            _context = context;
        }

        // GET: Admin/Seats
        public async Task<IActionResult> Index(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var room = _context.Rooms.Where(r => r.ID.Equals(id)).First();
            ViewBag.Room = room;
            ViewBag.Seat_Level = _context.Seat_Levels.ToList();
            var dPContext = _context.Seats.Include(s => s.Room).Include(s => s.Seat_Level).Where(s=>s.Room_ID.Equals(id));
            ViewBag.ListSeat = dPContext.ToList();
            return View();
        }

        // GET: Admin/Seats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seat = await _context.Seats
                .Include(s => s.Room)
                .Include(s => s.Seat_Level)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (seat == null)
            {
                return NotFound();
            }

            return View(seat);
        }

        // POST: Admin/Seats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Row_ID,Col_ID,Status,Room_ID,Seat_Level_ID")] Seat seat)
        {
            if (ModelState.IsValid)
            {
                _context.Add(seat);
                await _context.SaveChangesAsync();
                return Redirect("/Admin/Seats/Index/" + seat.Room_ID);
            }
            ViewData["Room_ID"] = new SelectList(_context.Rooms, "ID", "Name", seat.Room_ID);
            ViewData["Seat_Level_ID"] = new SelectList(_context.Seat_Levels, "ID", "Name", seat.Seat_Level_ID);
            return View(seat);
        }

        // GET: Admin/Seats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seat = await _context.Seats.FindAsync(id);
            if (seat == null)
            {
                return NotFound();
            }
            ViewData["Room_ID"] = new SelectList(_context.Rooms, "ID", "Name", seat.Room_ID);
            ViewData["Seat_Level_ID"] = new SelectList(_context.Seat_Levels, "ID", "Name", seat.Seat_Level_ID);
            return View(seat);
        }

        // POST: Admin/Seats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Row_ID,Col_ID,Status,Room_ID,Seat_Level_ID")] Seat seat)
        {
            if (id != seat.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(seat);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SeatExists(seat.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Redirect("/Admin/Seats/Index/" + seat.Room_ID);
            }
            ViewData["Room_ID"] = new SelectList(_context.Rooms, "ID", "Name", seat.Room_ID);
            ViewData["Seat_Level_ID"] = new SelectList(_context.Seat_Levels, "ID", "Name", seat.Seat_Level_ID);
            return View(seat);
        }

        // GET: Admin/Seats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seat = await _context.Seats
                .Include(s => s.Room)
                .Include(s => s.Seat_Level)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (seat == null)
            {
                return NotFound();
            }

            return View(seat);
        }

        // POST: Admin/Seats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var seat = await _context.Seats.FindAsync(id);
            _context.Seats.Remove(seat);
            await _context.SaveChangesAsync();
            return Redirect("/Admin/Seats/Index/" + seat.Room_ID);
        }

        private bool SeatExists(int id)
        {
            return _context.Seats.Any(e => e.ID == id);
        }
    }
}

CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Views/Rooms/Create.cshtml
@model WebAppCinemaBooking.Areas.Admin.Models.Room

@{
    ViewData["Title"] = "Create";
}

<h1>Thêm Phòng</h1>

<h4>Phòng</h4>
<hr />
<div class="row">
    <div class="col-md">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Tên Phòng:</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Sức Chứa:</label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Rạp Phim:</label>
                <select asp-for="Cinema_ID" class="form-control" asp-items="ViewBag.Cinema_ID"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Trạng Thái:</label>
                <select asp-for="Status" class="form-control">
                    <option value="1">Kích Hoạt</option>
                    <option value="0">Không Kích Hoạt</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Thêm" class="btn " style="width:300px;background-color: #26c6da;" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn " style="width:300px;margin-bottom: 10px;background-color: #1ea6c1;">Trở Về</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Views/Rooms/Delete.cshtml
@model WebAppCinemaBooking.Areas.Admin.Models.Room

@{
    ViewData["Title"] = "Delete";
}

<h1>Xóa Phòng</h1>

<h3>Bạn có chắc muốn xóa phòng này?</h3>
<div>
    <h4>Phòng</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Tên Phòng:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Sức Chứa:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class="col-sm-2">
            Trạng Thái:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class="col-sm-2">
            Rạp Phim:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cinema.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />

        <input type="submit" value="Xóa" class="btn" style="width: 300px;;margin-bottom: 10px;background-color: #26c6da;" />
        <br />
        <a asp-action="Index" class="btn" style="width: 300px;;margin-bottom: 10px;background-color: #1ea6c1;">Trở Về</a>

    </form>
</div>

CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Views/Rooms/Details.cshtml
@model WebAppCinemaBooking.Areas.Admin.Models.Room

@{
    ViewData["Title"] = "Details";
}

<h1>Chi Tiết Phòng</h1>

<div>
    <h4>Phòng</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
           Tên Phòng:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            Sức Chứa:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class = "col-sm-2">
           Trạng Thái:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            Rạp Phim:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cinema.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID" class="btn" style="width:300px;margin-bottom: 10px;background-color: #26c6da;">Sửa</a><br />
    <a asp-action="Index" class="btn" style="width:300px;margin-bottom: 10px;background-color: #1ea6c1;">Trở Về</a>
</div>

CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Views/Rooms/Edit.cshtml
@model WebAppCinemaBooking.Areas.Admin.Models.Room

@{
    ViewData["Title"] = "Edit";
}

<h1>Sửa Phòng</h1>

<h4>Phòng</h4>
<hr />
<div class="row">
    <div class="col-md">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label class="control-label">Tên Phòng:</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Sức Chứa:</label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Rạp Phim:</label>
                <select asp-for="Cinema_ID" class="form-control" asp-items="ViewBag.Cinema_ID"></select>
                <span asp-validation-for="Cinema_ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Trạng Thái:</label>
                <select asp-for="Status" class="form-control">
                    <option value="1">Kích Hoạt</option>
                    <option value="0">Không Kích Hoạt</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Thêm" class="btn " style="width:300px;background-color: #26c6da;" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn " style="width:300px;margin-bottom: 10px;background-color: #1ea6c1;">Trở Về</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Views/Rooms/Index.cshtml
@model IEnumerable<WebAppCinemaBooking.Areas.Admin.Models.Room>

@{
    ViewData["Title"] = "Index";
}
<style>
    th {
        text-align: center;
    }

    td {
        font-size: 16px;
        text-align: center;
        line-height: 40px;
    }

    button i.fa {
        font-size: 20px;
        display: block;
        line-height: 40px;
    }

        button i.fa.fa-lock {
            color: red;
        }

        button i.fa.fa-unlock-alt {
            color: green;
        }
</style>

<h1>Phòng</h1>

<p>
    <a asp-action="Create" class="btn btn-block" style="background-color: #26c6da;">Thêm Phòng</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Tên Phòng:
            </th>
            <th>
                Rạp Phim:
            </th>
            <th>
                Trạng Thái:
            </th>
            <th>Xem Sơ Đồ</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cinema.Name)
                </td>
                <td>
                    @if (item.Status == 1)
                    {
                        <button data-id="@item.ID" name="btnStatus" class="btn btn-link"><i class="fa fa-unlock-alt"></i></button>
                    }
                    else if (item.Status == 0)
                    {
                        <button data-id="@item.ID" name="btnStatus" class="btn btn-link"><i class="fa fa-lock"></i></button>
                    }
                </td>
                <td>
                    <a asp-area="Admin" asp-controller="Seats" asp-action="Index" asp-route-id="@item.ID"><label class="fa fa-eye"></label></a>
                </td>
                <td>
                    <div class="btn-group">
                        <a asp-action="Edit" asp-route-id="@item.ID" class="btn" style="background-color: #26c6da;">Sửa</a>
                        <a asp-action="Details" asp-route-id="@item.ID" class="btn" style="background-color: #1ea6c1;">Chi Tiết</a>
                        <a asp-action="Delete" asp-route-id="@item.ID" class="btn" style="background-color: #26c6da;">Xóa</a>
                    </div>
                </td>

            </tr>
        }
    </tbody>
</table>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $('button[name =btnStatus]').click(function () {
            var id = $(this).data('id');
            var btn = $(this);
            $.ajax({
                method: "GET",
                url: "../API/RoomsAPI/ChangeStatus",
                data: { 'id': id }
            })
                .done(function (msg) {
                var obj = JSON.parse(msg);
                if (obj.Status == 0) {
                    btn.children().removeClass('fa fa-unlock-alt');
                    btn.children().addClass('fa fa-lock');
                } else {
                    btn.children().removeClass('fa fa-lock');
                    btn.children().addClass('fa fa-unlock-alt');
                }
            });
        });
    </script>
}