CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAppCinemaBooking.Areas.Admin.Data;
using WebAppCinemaBooking.Areas.Admin.Models;

namespace WebAppCinemaBooking.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RoomsController : Controller
    {
        private readonly DPContext _context;

        public RoomsController(DPContext context)
        {
            _context = context;
        }

        // GET: Admin/Rooms
        public async Task<IActionResult> Index()
        {
            var dPContext = _context.Rooms.Include(r => r.Cinema);
            return View(await dPContext.ToListAsync());
        }

        // GET: Admin/Rooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .Include(r => r.Cinema)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Admin/Rooms/Create
        public IActionResult Create()
        {
            ViewData["Cinema_ID"] = new SelectList(_context.Cinemas, "ID", "Name");
            return View();
        }

        // POST: Admin/Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Capacity,Status,Cinema_ID")] Room room)
        {
            if (ModelState.IsValid)
            {
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Cinema_ID"] = new SelectList(_context.Cinemas, "ID", "Name", room.Cinema_ID);
            return View(room);
        }

        // GET: Admin/Rooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            ViewData["Cinema_ID"] = new SelectList(_context.Cinemas, "ID", "Name", room.Cinema_ID);
            return View(room);
        }

        // POST: Admin/Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Capacity,Status,Cinema_ID")] Room room)
        {
            if (id != room.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Cinema_ID"] = new SelectList(_context.Cinemas, "ID", "Name", room.Cinema_ID);
            return View(room);
        }

        // GET: Admin/Rooms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .Include(r => r.Cinema)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Admin/Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var room = await _context.Rooms.FindAsync(id);
            _context.Rooms.Remove(room);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
            return _context.Rooms.Any(e => e.ID == id);
        }
        public async Task<IActionResult> Active(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.ID == id);
            if (room == null)
            {
                return NotFound();
            }
            room.Status = 1;
            _context.Rooms.Update(room);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UnActive(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.ID == id);
            if (room == null)
            {
                return NotFound();
            }
            room.Status = 0;
            _context.Rooms.Update(room);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Controllers/StafsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAppCinemaBooking.Areas.Admin.Models;
using WebAppCinemaBooking.Areas.Admin.Data;

namespace WebAppCinemaBooking.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class StafsController : Controller
    {
        private readonly DPContext _context;

        public StafsController(DPContext context)
        {
            _context = context;
        }

        // GET: Admin/Stafs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Stafs.ToListAsync());
        }

        // GET: Admin/Stafs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staf = await _context.Stafs
                .FirstOrDefaultAsync(m => m.ID == id);
            if (staf == null)
            {
                return NotFound();
            }

            return View(staf);
        }

        // GET: Admin/Stafs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Stafs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Email,Password,Avatar,Phone,Address,Status")] Staf staf, IFormFile ful)
        {
            if (ModelState.IsValid)
            {
                _context.Add(staf);
                await _context.SaveChangesAsync();
                var tenImg = staf.ID + "." + ful.FileName.Split(".")[ful.FileName.Split(".").Length - 1];
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Uploads/Avatar-Staf", tenImg);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await ful.CopyToAsync(stream);

                }
                staf.Avatar = tenImg;
                _context.Update(staf);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(staf);
        }

        // GET: Admin/Stafs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staf = await _context.Stafs.FindAsync(id);
            if (staf == null)
            {
                return NotFound();
            }
            return View(staf);
        }

        // POST: Admin/Stafs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Email,Password,Avatar,Phone,Address,Status")] Staf staf)
        {
            if (id != staf.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(staf);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StafExists(staf.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(staf);
        }

        // GET: Admin/Stafs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staf = await _context.Stafs
                .FirstOrDefaultAsync(m => m.ID == id);
            if (staf == null)
            {
                return NotFound();
            }

            return View(staf);
        }

        // POST: Admin/Stafs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var staf = await _context.Stafs.FindAsync(id);
            _context.Stafs.Remove(staf);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StafExists(int id)
        {
            return _context.Stafs.Any(e => e.ID == id);
        }

        public async Task<IActionResult> Active(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staf = await _context.Stafs
                .FirstOrDefaultAsync(m => m.ID == id);
            if (staf == null)
            {
                return NotFound();
            }
            staf.Status = 1;
            _context.Stafs.Update(staf);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UnActive(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staf = await _context.Stafs
                .FirstOrDefaultAsync(m => m.ID == id);
            if (staf == null)
            {
                return NotFound();
            }
            staf.Status = 0;
            _context.Stafs.Update(staf);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Views/Shared/_FooterPartial.cshtml
<footer class="footer">
    MSSV: 0306181057 - Tên: Lê Minh Nhật - Lớp: CĐTH18PMA</a>
</footer>

CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Views/Shared/_HeadPartial.cshtml
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- Tell the browser to be responsive to screen width -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="keywords"
      content="wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 4 admin, bootstrap 4, css3 dashboard, bootstrap 4 dashboard, materialpro admin bootstrap 4 dashboard, frontend, responsive bootstrap 4 admin template, materialpro admin lite design, materialpro admin lite dashboard bootstrap 4 dashboard template">
<meta name="description"
      content="Material Pro Lite is powerful and clean admin dashboard template, inpired from Bootstrap Framework">
<meta name="robots" content="noindex,nofollow">
<title> @ViewBag.Title | TechBlog Admin</title>
<link rel="canonical" href="https://www.wrappixel.com/templates/materialpro-lite/" />
<!-- Favicon icon -->
<link rel="icon" type="image/png" sizes="16x16" href="~/admin-asset/assets/images/favicon.png">
<!-- chartist CSS -->
<link href="~/admin-asset/assets/plugins/chartist-js/dist/chartist.min.css" rel="stylesheet">
<link href="~/admin-asset/assets/plugins/chartist-js/dist/chartist-init.css" rel="stylesheet">
<link href="~/admin-asset/assets/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.css" rel="stylesheet">
<!--This page css - Morris CSS -->
<link href="~/admin-asset/assets/plugins/c3-master/c3.min.css" rel="stylesheet">
<!-- Custom CSS -->
<link href="~/admin-asset/asset/css/style.min.css" rel="stylesheet">
<Link rel="stylesheet" href="~/admin-asset/asset/css/icons/font-awesome/css/fontawesome-all.min.css">
<link rel="stylesheet" href="~/admin-asset/asset/css/icons/material-design-iconic-font/css/material-design-iconic-font.min.css" />
<link rel="stylesheet" href="~/admin-asset/asset/css/icons/material-design-iconic-font/css/materialdesignicons.min.css" />
<link rel="stylesheet" href="~/admin-asset/asset/css/icons/material-design-iconic-font/css/material-design-iconic-font.css" />
<link rel="stylesheet" href="~/admin-asset/asset/css/icons/themify-icons/themify-icons.css" />
<link rel="stylesheet" href="~/admin-asset/asset/css/icons/simple-line-icons/css/simple-line-icons.css" />
<link rel="stylesheet" href="~/admin-asset/asset/css/icons/weather-icons/css/weather-icons.min.css" />
<link rel="stylesheet" href="~/admin-asset/assets/plugins/bootstrap/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"/>
<script src="~/admin-asset/assets/plugins/jquery/dist/jquery.slim.min.js"></script>

CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Views/Shared/_HeaderPartial.cshtml
<header class="topbar" data-navbarbg="skin6">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header" data-logobg="skin6">
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <a class="navbar-brand ml-4" asp-area="Admin" asp-controller="Home" asp-action="Index">
                <!-- Logo icon -->
                <b class="logo-icon">
                    <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                    <!-- Dark Logo icon -->
                    <img src="~/admin-asset/assets/images/logo-light-icon.png" alt="homepage" class="dark-logo" />

                </b>
                <!--End Logo icon -->
                <!-- Logo text -->
                <span class="logo-text">
                    <!-- dark Logo text -->
                    <img src="~/admin-asset/assets/images/logo-light-text.png" alt="homepage" class="dark-logo" />

                </span>
            </a>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <a class="nav-toggler waves-effect waves-light text-white d-block d-md-none"
               href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
            <ul class="navbar-nav d-lg-none d-md-block ">
                <li class="nav-item">
                    <a class="nav-toggler nav-link waves-effect waves-light text-white "
                       href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
                </li>
            </ul>
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav mr-auto mt-md-0 ">
                <!-- ============================================================== -->
                <!-- Search -->
                <!-- ============================================================== -->

                <li class="nav-item search-box">
                    <a class="nav-link text-muted" href="javascript:void(0)"><i class="ti-search"></i></a>
                    <form class="app-search" style="display: none;">
                        <input type="text" class="form-control" placeholder="Search &amp; enter"> <a class="srh-btn"><i class="ti-close"></i></a>
                    </form>
                </li>
            </ul>

            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav">
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark" href=""
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="~/admin-asset/assets/images/users/1.jpg" alt="user" class="profile-pic m-r-10">Markarn Doe
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</header>

CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    @await Html.PartialAsync("_HeadPartial.cshtml")
</head>
<body>
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full" data-sidebar position="absolute" data-header-position="absolute" data-boxed-layout="full">
        @await Html.PartialAsync("_HeaderPartial.cshtml")
        @await Html.PartialAsync("_SideBarPartial.cshtml")
        <div class="page-wrapper">
            <div class="container-fluid">
                <div class="card">
                    <div class="container-fluid">
                        @RenderBody()
                    </div>
                </div>
            </div>
            @await Html.PartialAsync("_FooterPartial.cshtml")
        </div>
    </div>
    @await Html.PartialAsync("_ScriptPartial.cshtml")
</body>
@RenderSection("Scripts", required: false)
</html>

CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Views/Shared/_ScriptPartial.cshtml
<script src="~/admin-asset/assets/plugins/jquery/dist/jquery.min.js"></script>

<!-- Bootstrap tether Core JavaScript -->
<script src="~/admin-asset/assets/plugins/popper.js/dist/umd/popper.min.js"></script>
<script src="~/admin-asset/assets/plugins/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="~/admin-asset/asset/js/app-style-switcher.js"></script>
<!--Wave Effects -->
<script src="~/admin-asset/asset/js/waves.js"></script>
<!--Menu sidebar -->
<script src="~/admin-asset/asset/js/sidebarmenu.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<!-- ============================================================== -->
<!-- This page plugins -->
<!-- ============================================================== -->
<!-- chartist chart -->
<script src="~/admin-asset/assets/plugins/chartist-js/dist/chartist.min.js"></script>
<script src="~/admin-asset/assets/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.min.js"></script>
<!--c3 JavaScript -->
<script src="~/admin-asset/assets/plugins/d3/d3.min.js"></script>
<script src="~/admin-asset/assets/plugins/c3-master/c3.min.js"></script>
<!--Custom JavaScript -->
<script src="~/admin-asset/asset/js/pages/dashboards/dashboard1.js"></script>
<script src="~/admin-asset/asset/js/custom.js"></script>

<script src="~/admin-asset/ckeditor/ckeditor.js"></script>
<script>
    CKEDITOR.replace('content');
    CKEDITOR.replace('desc');

</script>

CinemaBookingTicket/WebAppCinemaBooking/Areas/Admin/Views/Shared/_SideBarPartial.cshtml
<aside class="left-sidebar" data-sidebarbg="skin6">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <!-- User Profile-->
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link"
                       asp-area="Admin" asp-controller="Home" asp-action="Index" aria-expanded="false">
                        <i class="mdi mr-2 mdi-gauge"></i><span class="hide-menu">Tổng Quan</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link"
                       asp-area="Admin" asp-controller="Stafs" asp-action="Index" aria-expanded="false">
                        <i class="mdi mr-2 mdi-format-list-bulleted"></i><span class="hide-menu">Quản Lí Nhân Viên</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link"
                       asp-area="Admin" asp-controller="Cinemas" asp-action="Index" aria-expanded="false">
                        <i class="mdi mr-2 mdi-newspaper"></i><span class="hide-menu">Quản Lí Rạp Phim</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link"
                       asp-area="Admin" asp-controller="Rooms" asp-action="Index" aria-expanded="false">
                        <i class="mdi mr-2 mdi-home"></i><span class="hide-menu">Quản Lí Phòng</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link"
                       asp-area="Admin" asp-controller="Seat_Level" asp-action="Index" aria-expanded="false">
                        <i class="mdi mr-2 mdi-format-list-bulleted"></i><span class="hide-menu">Quản Lí Loại Ghế</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link"
                       asp-area="Admin" asp-controller="Movies" asp-action="Index" aria-expanded="false">
                        <i class="mdi mr-2 mdi-format-list-bulleted"></i><span class="hide-menu">Quản Lí Phim</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link"
                       asp-area="Admin" asp-controller="Customers" asp-action="Index" aria-expanded="false">
                        <i class="mdi mr-2 mdi-format-list-bulleted"></i><span class="hide-menu">Quản Lí Khách Hàng</span>
                    </a>
                </li>

            </ul>

        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
    <div class="sidebar-footer">
        <div class="row">
            <div class="col-4 link-wrap">
                <!-- item-->
                <a href="" class="link" data-toggle="tooltip" title="" data-original-title="Settings">
                    <i class="ti-settings"></i>
                </a>
            </div>
            <div class="col-4 link-wrap">
                <!-- item-->
                <a href="" class="link" data-toggle="tooltip" title="" data-original-title="Email">
                    <i class="mdi mdi-gmail"></i>
                </a>
            </div>
            <div class="col-4 link-wrap">
                <!-- item-->
                <a href="" class="link" data-toggle="tooltip" title="" data-original-title="Logout">
                    <i class="mdi mdi-power"></i>
                </a>
            </div>
        </div>
    </div>
</aside>